name: pokedex_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '^3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  go_router: ^7.1.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  intl: ^0.18.0
  graphql_flutter: ^5.1.2
  flutter_svg: ^2.0.6
  vector_graphics_compiler: ^1.1.6
  vector_graphics: ^1.1.6
  string_to_hex: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/pokemon_type/pokemon_type_icons/
    - assets/pokemon_type/pokemon_type_color.json
    - assets/card_pokeball.svg.vec